# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "haili58"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
chip = "nrf52840"

# [matrix]
# Not used for split keyboards


[layout]
rows = 10
cols = 6
layers = 2
keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "Y"],
        ["LCtrl", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["LAlt", "LGui", "Space", "Delete", "Enter", "AudioMute"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backspace"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "J", "K", "L", "Semicolon", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "Enter"],
        ["MO(1)", "MO(1)", "Space", "Delete", "Enter", "AudioMute"]
    ],
    [
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"]
    ],
]



[storage]
# Storage feature is enabled by default
# enabled = false

[split]
connection = "ble"

[split.central]
rows = 10
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_12", "P0_13"]
col_pins = ["P0_14", "P0_15"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_11", "P1_04", "P1_06", "P0_09", "P0_10"]
col_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 5
[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_11", "P1_04", "P1_06", "P0_09", "P0_10"]
col_pins = ["P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31"]